spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lmsku?useSSL=false&serverTimezone=Asia/Jakarta
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
